# Generated by Django 5.2 on 2025-04-22 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_saved_recipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipes', models.ManyToManyField(blank=True, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grocery List',
                'verbose_name_plural': 'Grocery Lists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('pantry', 'Pantry'), ('frozen', 'Frozen'), ('beverages', 'Beverages'), ('other', 'Other')], default='other', max_length=20)),
                ('checked', models.BooleanField(default=False)),
                ('custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recipes.grocerylist')),
            ],
            options={
                'verbose_name': 'Grocery Item',
                'verbose_name_plural': 'Grocery Items',
                'ordering': ['category', 'ingredient'],
            },
        ),
    ]
